"""add privacy accepted flag

Revision ID: 9412753a0e89
Revises: e7cd35bd27a0
Create Date: 2025-04-24 16:16:28.281863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9412753a0e89"
down_revision: Union[str, None] = "e7cd35bd27a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("privacy_accepted", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "privacy_accepted")
    # ### end Alembic commands ###
