"""add_user_language_code

Revision ID: e7cd35bd27a0
Revises: 7f353757bac3
Create Date: 2025-04-24 14:36:16.438126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7cd35bd27a0"
down_revision: Union[str, None] = "7f353757bac3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("language_code", sa.String(length=5), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language_code")
    # ### end Alembic commands ###
