"""daylight hours

Revision ID: 586e08ea27af
Revises: afb2fc8c80cd
Create Date: 2025-06-09 06:35:30.123634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "586e08ea27af"
down_revision: Union[str, None] = "afb2fc8c80cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "day_start",
            sa.Time(),
            server_default=sa.text("'08:00:00'"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "day_end",
            sa.Time(),
            server_default=sa.text("'22:00:00'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_users_daylight_order",
        "users",
        "day_start < day_end",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_users_daylight_order", "users", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "day_end")
    op.drop_column("users", "day_start")
    # ### end Alembic commands ###
