services:
  mariadb:
    image: mariadb:lts
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: medtimely
      MARIADB_USER: medtimely
      MARIADB_PASSWORD: medtimely

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    image: med-timely-bot
    build: .
    environment:
      - BOT__TOKEN=${BOT__TOKEN}
      - DB__URL=mariadb+asyncmy://medtimely:medtimely@mariadb/medtimely
      - REDIS__URL=redis://redis:6379/0
      - LLM__API_KEY=${LLM__API_KEY}
      - RUN_MIGRATIONS=true
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-worker:
    build: .
    environment:
      - BOT__TOKEN=${BOT__TOKEN}
      - DB__URL=mariadb+asyncmy://medtimely:medtimely@mariadb/medtimely
      - REDIS__URL=redis://redis:6379/0
      - LLM__API_KEY=${LLM__API_KEY}
    command: celery -A src.tasks.celery worker --loglevel=info
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build: .
    command: celery -A src.tasks.celery beat --loglevel=info
    environment:
      - BOT__TOKEN=${BOT__TOKEN}
      - DB__URL=mariadb+asyncmy://medtimely:medtimely@mariadb/medtimely
      - REDIS__URL=redis://redis:6379/0
      - LLM__API_KEY=${LLM__API_KEY}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mariadb_data:
